"""Cambios base de datos

Revision ID: 874897d5d732
Revises: 
Create Date: 2024-08-10 09:22:09.692024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '874897d5d732'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comentario', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('comentario', 'fecha_creacion')
    op.add_column('reporte', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('reporte', 'comentario')
    op.add_column('serpientes', sa.Column('descripcion', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serpientes', 'descripcion')
    op.add_column('reporte', sa.Column('comentario', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('reporte', 'created_at')
    op.add_column('comentario', sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('comentario', 'created_at')
    # ### end Alembic commands ###
